# Generated by Django 4.1.7 on 2023-03-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='allergy',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='diet',
            field=models.SmallIntegerField(choices=[(-1, '다이어트'), (0, '유지'), (1, '증량')], null=True),
        ),
    ]
