# Generated by Django 4.1.7 on 2023-03-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_age_alter_customuser_allergy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='allergy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='diet',
            field=models.SmallIntegerField(blank=True, choices=[(-1, '다이어트'), (0, '유지'), (1, '증량')], null=True),
        ),
    ]
