# Generated by Django 4.1.7 on 2023-05-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KoreanRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcp_seq', models.IntegerField()),
                ('rcp_nm', models.CharField(max_length=200)),
                ('rcp_way2', models.CharField(blank=True, max_length=100, null=True)),
                ('rcp_pat2', models.CharField(blank=True, max_length=100, null=True)),
                ('info_wgt', models.FloatField(blank=True, null=True)),
                ('info_eng', models.FloatField(blank=True, null=True)),
                ('info_car', models.FloatField(blank=True, null=True)),
                ('info_pro', models.FloatField(blank=True, null=True)),
                ('info_fat', models.FloatField(blank=True, null=True)),
                ('info_na', models.FloatField(blank=True, null=True)),
                ('hash_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('att_file_no_main', models.CharField(blank=True, max_length=500, null=True)),
                ('att_file_no_mk', models.CharField(blank=True, max_length=500, null=True)),
                ('rcp_parts_dtls', models.CharField(blank=True, max_length=500, null=True)),
                ('manual01', models.CharField(blank=True, max_length=500, null=True)),
                ('manual_img01', models.CharField(blank=True, max_length=500, null=True)),
                ('manual02', models.CharField(blank=True, max_length=500, null=True)),
                ('manual_img02', models.CharField(blank=True, max_length=500, null=True)),
                ('manual03', models.CharField(blank=True, max_length=500, null=True)),
                ('manual_img03', models.CharField(blank=True, max_length=500, null=True)),
                ('manual04', models.CharField(blank=True, max_length=500, null=True)),
                ('manual_img04', models.CharField(blank=True, max_length=500, null=True)),
                ('manual05', models.CharField(blank=True, max_length=500, null=True)),
                ('manual_img05', models.CharField(blank=True, max_length=500, null=True)),
                ('manual06', models.CharField(blank=True, max_length=500, null=True)),
                ('manual_img06', models.CharField(blank=True, max_length=500, null=True)),
                ('raw', models.CharField(blank=True, max_length=500, null=True)),
                ('parsed', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
