# Generated by Django 4.1.7 on 2023-04-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerators', '0002_grocery_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='image',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
