# Generated by Django 4.1.7 on 2023-04-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerators', '0003_remove_grocery_image_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
