# Generated by Django 4.1.7 on 2023-04-14 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerators', '0004_grocery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='exp_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grocery'),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='in_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
