# Generated by Django 4.1.7 on 2023-04-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerators', '0005_alter_grocery_exp_date_alter_grocery_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='insertion_method',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'Picture'), (2, 'Direct')], default=0),
        ),
    ]
