# Generated by Django 4.1.7 on 2023-04-20 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refrigerators', '0006_grocery_insertion_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='parsed_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grocery',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grocery',
            name='insertion_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('picture', 'Picture'), ('barcode', 'Barcode')], default='manual', max_length=50),
        ),
    ]
