# Generated by Django 4.1.7 on 2023-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerators', '0008_alter_grocery_parsed_name_alter_grocery_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='category',
            field=models.CharField(choices=[('processed_meat', '가공육류'), ('grain', '곡류'), ('fruit', '과일류'), ('snack', '과자'), ('oil', '기름류'), ('other_processed', '기타가공품'), ('extract', '기타추출물'), ('agricultural', '농산가공품'), ('glucose', '당류'), ('bean_processed', '두류가공품'), ('ricecake', '떡류'), ('noodle', '면류'), ('sugar_salt', '설탕소금류'), ('processed_marine', '수산물가공품'), ('seasoning', '양념'), ('milk', '우유'), ('dairy', '유제품'), ('meat', '육류'), ('drink', '음료류'), ('ginseng_yeast', '인삼효모류'), ('powder', '전분류'), ('pickle', '절임식품'), ('jelly', '젤리류'), ('braised', '조림류'), ('alcohol', '주류'), ('vegetable', '채소류'), ('chocolate', '초콜릿가공품'), ('spice', '향신료')], default='grain', max_length=50),
        ),
    ]
