# Generated by Django 4.1.7 on 2023-04-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerators', '0009_alter_grocery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeInfo',
            fields=[
                ('bar_id', models.IntegerField()),
                ('barcode', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('pd_name', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('re_category', models.CharField(default='', max_length=500)),
                ('best_before', models.IntegerField()),
                ('supplier', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('icon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('re_category', models.CharField(default='', max_length=500)),
                ('icon_img', models.BinaryField(blank=True)),
            ],
        ),
    ]
